# SPDX-License-Identifier: MIT
# Copyright (c) 2022-2023 Jamf

name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.swift'

# Kill any previous run still executing
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Unit Tests:
    runs-on: macos-latest
    name: Run unit tests

    steps:
    - uses: actions/checkout@v3
    - name: Unit Test (macOS)
      run: swift test -v

    - name: Unit Test (iOS)
      run: xcodebuild test -scheme ManagedAppConfigLib -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 13"

    - name: Unit Test (tvOS)
      run: xcodebuild test -scheme ManagedAppConfigLib -sdk appletvsimulator16.1 -destination "OS=16.1,name=Apple TV"
