name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.swift'

# Kill any previous run still executing
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  spm_tests:
    name: Run package tests
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Unit Test
      run: swift test -v
